[[cases]]
name = "published_defaults"
generations = 100
initial_size = 1.0
initial_vector = "geci-published_defaults-initial.tsv"
[cases.parameters]
Rm = 6.0
theta = 0.1
c = 1.0
s_f = 0.0
h_f = 0.5
s_m = 0.0
s_a = 0.0
s_b = 0.0
s_c = 0.0
s_d = 0.0
s_e = 0.0
h_e = 0.5
e_e = 0.95
e_h = 0.95
m_1 = 0.0
m_2 = 0.0
e_s = 0.95
h_e2 = 0.5
er_1 = 0.0
er_2 = 0.0
er_3 = 0.0
r = 0.0
[[cases]]
name = "upstream_parameters"
generations = 100
initial_size = 1.0
initial_vector = "geci-upstream_parameters-initial.tsv"
[cases.parameters]
Rm = 6.0
theta = 0.1
c = 1.0
s_f = 1.0
h_f = 1.0
s_m = 0.0
s_a = 0.0
s_b = 0.0
s_c = 0.0
s_d = 0.0
s_e = 0.0
h_e = 1.0
e_e = 0.95
e_h = 0.953
m_1 = 0.0
m_2 = 0.0
e_s = 0.947368
h_e2 = 1.0
er_1 = 0.0
er_2 = 0.0
er_3 = 0.0
r = 0.5
[[cases]]
name = "nonzero_costs_and_resistance"
generations = 100
initial_size = 1.0
initial_vector = "geci-nonzero_costs_and_resistance-initial.tsv"
[cases.parameters]
Rm = 6.0
theta = 0.1
c = 1.0
s_f = 0.7
h_f = 0.5
s_m = 0.1
s_a = 0.05
s_b = 0.06
s_c = 0.07
s_d = 0.08
s_e = 0.09
h_e = 0.5
e_e = 0.95
e_h = 0.95
m_1 = 0.01
m_2 = 0.001
e_s = 0.95
h_e2 = 0.5
er_1 = 0.02
er_2 = 0.03
er_3 = 0.04
r = 0.2
[[cases]]
name = "no_release"
generations = 100
initial_size = 1.0
initial_vector = "geci-no_release-initial.tsv"
[cases.parameters]
Rm = 6.0
theta = 0.1
c = 1.0
s_f = 0.0
h_f = 0.5
s_m = 0.0
s_a = 0.0
s_b = 0.0
s_c = 0.0
s_d = 0.0
s_e = 0.0
h_e = 0.5
e_e = 0.95
e_h = 0.95
m_1 = 0.0
m_2 = 0.0
e_s = 0.95
h_e2 = 0.5
er_1 = 0.0
er_2 = 0.0
er_3 = 0.0
r = 0.0
